name: My First Workflow
on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps: |
        run: echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
        run: echo "My secret is ${{ secrets.MY_SECRET }}"
    
