name: My First Workflow
on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello world from ${{ github..actor }}."
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - run: tree
    
